//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outreach_FRMS_Utility {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Outreach_FRMS_Utility.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sushilk3@chetu.com.
        /// </summary>
        public static string AdminEmail {
            get {
                return ResourceManager.GetString("AdminEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationInvitee.
        /// </summary>
        public static string ApplicationInviteeAPI {
            get {
                return ResourceManager.GetString("ApplicationInviteeAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Invitation Send Successfully..
        /// </summary>
        public static string ApplicationInviteMessage {
            get {
                return ResourceManager.GetString("ApplicationInviteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationInvite.
        /// </summary>
        public static string ApplicationInviteMethod {
            get {
                return ResourceManager.GetString("ApplicationInviteMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_SaveApplicationInvitee.
        /// </summary>
        public static string ApplicationInviteSP {
            get {
                return ResourceManager.GetString("ApplicationInviteSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BusinessCategoryList.
        /// </summary>
        public static string BusinessCategoryListAPI {
            get {
                return ResourceManager.GetString("BusinessCategoryListAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BusinessClaimGet.
        /// </summary>
        public static string BusinessClaimGetMethod {
            get {
                return ResourceManager.GetString("BusinessClaimGetMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BusinessClaimSave.
        /// </summary>
        public static string BusinessClaimSaveMethod {
            get {
                return ResourceManager.GetString("BusinessClaimSaveMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BusinessProfileData.
        /// </summary>
        public static string BusinessProfileDataMethod {
            get {
                return ResourceManager.GetString("BusinessProfileDataMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BusinessProfileUpdate.
        /// </summary>
        public static string BusinessProfileUpdateMethod {
            get {
                return ResourceManager.GetString("BusinessProfileUpdateMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check email to reset the password..
        /// </summary>
        public static string CheckEmailResetPassword {
            get {
                return ResourceManager.GetString("CheckEmailResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact added successfully..
        /// </summary>
        public static string ContactAddSuccess {
            get {
                return ResourceManager.GetString("ContactAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This contact is already saved by this user..
        /// </summary>
        public static string ContactAlreadySaved {
            get {
                return ResourceManager.GetString("ContactAlreadySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact delete duccessfully..
        /// </summary>
        public static string ContactDeleteMessage {
            get {
                return ResourceManager.GetString("ContactDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact already exist..
        /// </summary>
        public static string ContactExist {
            get {
                return ResourceManager.GetString("ContactExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_GetCountryList.
        /// </summary>
        public static string ContryListSP {
            get {
                return ResourceManager.GetString("ContryListSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data saved successfully..
        /// </summary>
        public static string DataSaved {
            get {
                return ResourceManager.GetString("DataSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_DeleteApplicationInvitee.
        /// </summary>
        public static string DeleteApplicationInvitee {
            get {
                return ResourceManager.GetString("DeleteApplicationInvitee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteContact.
        /// </summary>
        public static string DeleteContact {
            get {
                return ResourceManager.GetString("DeleteContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_DeleteContactInvitee.
        /// </summary>
        public static string DeleteContactInviteeSP {
            get {
                return ResourceManager.GetString("DeleteContactInviteeSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_DeleteContact.
        /// </summary>
        public static string DeleteContactSP {
            get {
                return ResourceManager.GetString("DeleteContactSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteDocument.
        /// </summary>
        public static string DeleteDocument {
            get {
                return ResourceManager.GetString("DeleteDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document delete successfully..
        /// </summary>
        public static string DeleteDocumentResponse {
            get {
                return ResourceManager.GetString("DeleteDocumentResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_DeleteUserDocument.
        /// </summary>
        public static string DeleteDocumentSP {
            get {
                return ResourceManager.GetString("DeleteDocumentSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteMyFav.
        /// </summary>
        public static string DeleteMyFav {
            get {
                return ResourceManager.GetString("DeleteMyFav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My fav delete successfully..
        /// </summary>
        public static string DeleteMyFavMessage {
            get {
                return ResourceManager.GetString("DeleteMyFavMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_DeleteMyFavs.
        /// </summary>
        public static string DeleteMyFavsSP {
            get {
                return ResourceManager.GetString("DeleteMyFavsSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User document does not exist..
        /// </summary>
        public static string DocumentNotExist {
            get {
                return ResourceManager.GetString("DocumentNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document upload successfully..
        /// </summary>
        public static string DocumentUploadSuccess {
            get {
                return ResourceManager.GetString("DocumentUploadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAKV2SPBNI99212.
        /// </summary>
        public static string EncryptionKey {
            get {
                return ResourceManager.GetString("EncryptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {MethodName} method executed successfully..
        /// </summary>
        public static string ExecutedSuccessfully {
            get {
                return ResourceManager.GetString("ExecutedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeedbackSave.
        /// </summary>
        public static string FeedbackSaveMethod {
            get {
                return ResourceManager.GetString("FeedbackSaveMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForgotPassword.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenerateJwtToken.
        /// </summary>
        public static string GenerateJwtToken {
            get {
                return ResourceManager.GetString("GenerateJwtToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_GetApplicationInviteeList.
        /// </summary>
        public static string GetAppInviteListSP {
            get {
                return ResourceManager.GetString("GetAppInviteListSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetApplicationInvite.
        /// </summary>
        public static string GetApplicationInviteMethod {
            get {
                return ResourceManager.GetString("GetApplicationInviteMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_GetBusinessCategory.
        /// </summary>
        public static string GetBusinessCategorySP {
            get {
                return ResourceManager.GetString("GetBusinessCategorySP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetBusinessClaim.
        /// </summary>
        public static string GetBusinessClaimAPI {
            get {
                return ResourceManager.GetString("GetBusinessClaimAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_GetBusinessClaimData.
        /// </summary>
        public static string GetBusinessClaimedDataSP {
            get {
                return ResourceManager.GetString("GetBusinessClaimedDataSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetBusinessProfile.
        /// </summary>
        public static string GetBusinessProfileAPI {
            get {
                return ResourceManager.GetString("GetBusinessProfileAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_GetBusinessProfile.
        /// </summary>
        public static string GetBusinessProfileSP {
            get {
                return ResourceManager.GetString("GetBusinessProfileSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_GetBusinessSubCategory.
        /// </summary>
        public static string GetBusinessSubCategorySP {
            get {
                return ResourceManager.GetString("GetBusinessSubCategorySP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_GetBusinessType.
        /// </summary>
        public static string GetBusinessTypeSP {
            get {
                return ResourceManager.GetString("GetBusinessTypeSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetCategoryList.
        /// </summary>
        public static string GetCategoryListMethod {
            get {
                return ResourceManager.GetString("GetCategoryListMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetBusinessClaimList.
        /// </summary>
        public static string GetClaimListMethod {
            get {
                return ResourceManager.GetString("GetClaimListMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_GetBusinessClaimList.
        /// </summary>
        public static string GetClaimListSP {
            get {
                return ResourceManager.GetString("GetClaimListSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_GetContactData.
        /// </summary>
        public static string GetContactDataSP {
            get {
                return ResourceManager.GetString("GetContactDataSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_GetContactList.
        /// </summary>
        public static string GetContactListSP {
            get {
                return ResourceManager.GetString("GetContactListSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetContactsList.
        /// </summary>
        public static string GetContactsList {
            get {
                return ResourceManager.GetString("GetContactsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetCountryList.
        /// </summary>
        public static string GetCountryListAPI {
            get {
                return ResourceManager.GetString("GetCountryListAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetCountry.
        /// </summary>
        public static string GetCountryMethod {
            get {
                return ResourceManager.GetString("GetCountryMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetInviteeList.
        /// </summary>
        public static string GetInviteeList {
            get {
                return ResourceManager.GetString("GetInviteeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_GetInviteeList.
        /// </summary>
        public static string GetInviteeListSP {
            get {
                return ResourceManager.GetString("GetInviteeListSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_GetInviteeContact.
        /// </summary>
        public static string GetInviteeSP {
            get {
                return ResourceManager.GetString("GetInviteeSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetInvitorList.
        /// </summary>
        public static string GetInvitorList {
            get {
                return ResourceManager.GetString("GetInvitorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_GetInvitorContact.
        /// </summary>
        public static string GetInvitorSP {
            get {
                return ResourceManager.GetString("GetInvitorSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetLeaderBoard.
        /// </summary>
        public static string GetLeaderBoardMethod {
            get {
                return ResourceManager.GetString("GetLeaderBoardMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_GetMyFavs.
        /// </summary>
        public static string GetListMyFavsSP {
            get {
                return ResourceManager.GetString("GetListMyFavsSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_GetUsers.
        /// </summary>
        public static string GetListSP {
            get {
                return ResourceManager.GetString("GetListSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetMyContactFavList.
        /// </summary>
        public static string GetMyContactFavList {
            get {
                return ResourceManager.GetString("GetMyContactFavList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_GetMyContactFavsList.
        /// </summary>
        public static string GetMyContactFavListSP {
            get {
                return ResourceManager.GetString("GetMyContactFavListSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_GetMyContactFavsData.
        /// </summary>
        public static string GetMyContactFavSP {
            get {
                return ResourceManager.GetString("GetMyContactFavSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetMyFavsList.
        /// </summary>
        public static string GetMyFavsList {
            get {
                return ResourceManager.GetString("GetMyFavsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_GetMyFavsList.
        /// </summary>
        public static string GetMyFavsListSP {
            get {
                return ResourceManager.GetString("GetMyFavsListSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_GetMyFavs.
        /// </summary>
        public static string GetMyFavsSP {
            get {
                return ResourceManager.GetString("GetMyFavsSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetOtherLeaderBoard.
        /// </summary>
        public static string GetOtherLeaderBoard {
            get {
                return ResourceManager.GetString("GetOtherLeaderBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_GetOthersInLeaderBoard.
        /// </summary>
        public static string GetOtherLeaderBoardSP {
            get {
                return ResourceManager.GetString("GetOtherLeaderBoardSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetRestaurantData.
        /// </summary>
        public static string GetRestaurantData {
            get {
                return ResourceManager.GetString("GetRestaurantData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_GetRestaurantDataMyContactFavs.
        /// </summary>
        public static string GetRestaurantDataMyContactfavsSP {
            get {
                return ResourceManager.GetString("GetRestaurantDataMyContactfavsSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_GetRestaurantDataMyFavs.
        /// </summary>
        public static string GetRestaurantDataMyfavsSP {
            get {
                return ResourceManager.GetString("GetRestaurantDataMyfavsSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_GetRestaurantDataOthers.
        /// </summary>
        public static string GetRestaurantDataOthersfavsSP {
            get {
                return ResourceManager.GetString("GetRestaurantDataOthersfavsSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_GetRestaurantData.
        /// </summary>
        public static string GetRestaurantDataSP {
            get {
                return ResourceManager.GetString("GetRestaurantDataSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetRestaurantList.
        /// </summary>
        public static string GetRestaurantList {
            get {
                return ResourceManager.GetString("GetRestaurantList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetServiceDataList.
        /// </summary>
        public static string GetServiceDataListMethod {
            get {
                return ResourceManager.GetString("GetServiceDataListMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_GetServiceDataList.
        /// </summary>
        public static string GetServiceDataListSP {
            get {
                return ResourceManager.GetString("GetServiceDataListSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_GetUserData.
        /// </summary>
        public static string GetUserDataSP {
            get {
                return ResourceManager.GetString("GetUserDataSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetUserDetails.
        /// </summary>
        public static string GetUserDetails {
            get {
                return ResourceManager.GetString("GetUserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_GetUserDocumentData.
        /// </summary>
        public static string GetUserDocDataSP {
            get {
                return ResourceManager.GetString("GetUserDocDataSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetUserList.
        /// </summary>
        public static string GetUserList {
            get {
                return ResourceManager.GetString("GetUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetUsers.
        /// </summary>
        public static string GetUsers {
            get {
                return ResourceManager.GetString("GetUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_GetUserList.
        /// </summary>
        public static string GetUsersMethod {
            get {
                return ResourceManager.GetString("GetUsersMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation already send for this user and sending again..
        /// </summary>
        public static string InvitationAlreadySentMessage {
            get {
                return ResourceManager.GetString("InvitationAlreadySentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation send successfully..
        /// </summary>
        public static string InvitationMessage {
            get {
                return ResourceManager.GetString("InvitationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitee.
        /// </summary>
        public static string Invitee {
            get {
                return ResourceManager.GetString("Invitee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitee does not exist..
        /// </summary>
        public static string InviteeDoesNotExistMessage {
            get {
                return ResourceManager.GetString("InviteeDoesNotExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InviteeList.
        /// </summary>
        public static string InviteeList {
            get {
                return ResourceManager.GetString("InviteeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status update successfully..
        /// </summary>
        public static string InviteeStatusUpdateMessage {
            get {
                return ResourceManager.GetString("InviteeStatusUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitor.
        /// </summary>
        public static string Invitor {
            get {
                return ResourceManager.GetString("Invitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitor does not exist..
        /// </summary>
        public static string InvitorDoesNotExistMessage {
            get {
                return ResourceManager.GetString("InvitorDoesNotExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitor or Invitee does not exist..
        /// </summary>
        public static string InvotorOrInviteeNotExistMessage {
            get {
                return ResourceManager.GetString("InvotorOrInviteeNotExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeaderBoard.
        /// </summary>
        public static string LeaderBoardAPI {
            get {
                return ResourceManager.GetString("LeaderBoardAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is incorrect.
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successfully !.
        /// </summary>
        public static string LoginResponseMessage {
            get {
                return ResourceManager.GetString("LoginResponseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {MethodName} method starts with request parameters : {RequestParameter}.
        /// </summary>
        public static string LoginStartMessage {
            get {
                return ResourceManager.GetString("LoginStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {MethodName} service starts.
        /// </summary>
        public static string LogServiceStartMessage {
            get {
                return ResourceManager.GetString("LogServiceStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogStartMessage.
        /// </summary>
        public static string LogStartMessage {
            get {
                return ResourceManager.GetString("LogStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyContactFavSave.
        /// </summary>
        public static string MyContactFavSave {
            get {
                return ResourceManager.GetString("MyContactFavSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyFavsSave.
        /// </summary>
        public static string MyFavsSave {
            get {
                return ResourceManager.GetString("MyFavsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyProfileUpdate.
        /// </summary>
        public static string MyProfileUpdate {
            get {
                return ResourceManager.GetString("MyProfileUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password update successfully..
        /// </summary>
        public static string PasswordUpdateSuccess {
            get {
                return ResourceManager.GetString("PasswordUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResetPassword.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_ResetPassword.
        /// </summary>
        public static string ResetPasswordSP {
            get {
                return ResourceManager.GetString("ResetPasswordSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestaurantDataSave.
        /// </summary>
        public static string RestaurantDataSaveMethod {
            get {
                return ResourceManager.GetString("RestaurantDataSaveMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Restaurant does not exist..
        /// </summary>
        public static string RestaurantNotExist {
            get {
                return ResourceManager.GetString("RestaurantNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Restaurant already favs by your contact friend id..
        /// </summary>
        public static string RestraurantAlreadyFavsByYourContactId {
            get {
                return ResourceManager.GetString("RestraurantAlreadyFavsByYourContactId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_SaveClaimBusiness.
        /// </summary>
        public static string SaveBusinessClaimSP {
            get {
                return ResourceManager.GetString("SaveBusinessClaimSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveClaimBusiness.
        /// </summary>
        public static string SaveClaimBusinessAPI {
            get {
                return ResourceManager.GetString("SaveClaimBusinessAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveContact.
        /// </summary>
        public static string SaveContact {
            get {
                return ResourceManager.GetString("SaveContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_SaveContact.
        /// </summary>
        public static string SaveContactSP {
            get {
                return ResourceManager.GetString("SaveContactSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveFeedback.
        /// </summary>
        public static string SaveFeedbackAPI {
            get {
                return ResourceManager.GetString("SaveFeedbackAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_SaveFeedback.
        /// </summary>
        public static string SaveFeedbackSP {
            get {
                return ResourceManager.GetString("SaveFeedbackSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_SaveInvitee.
        /// </summary>
        public static string SaveInviteeSP {
            get {
                return ResourceManager.GetString("SaveInviteeSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_SaveInvitor.
        /// </summary>
        public static string SaveInvitorSP {
            get {
                return ResourceManager.GetString("SaveInvitorSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_SaveMyContactFavs.
        /// </summary>
        public static string SaveMyContactFavSP {
            get {
                return ResourceManager.GetString("SaveMyContactFavSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_SaveMyFavs.
        /// </summary>
        public static string SaveMyFavsSP {
            get {
                return ResourceManager.GetString("SaveMyFavsSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveRestaurant.
        /// </summary>
        public static string SaveRestaurantAPI {
            get {
                return ResourceManager.GetString("SaveRestaurantAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_SaveExternalServiceData.
        /// </summary>
        public static string SaveRestaurantDataSP {
            get {
                return ResourceManager.GetString("SaveRestaurantDataSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_SaveServiceData.
        /// </summary>
        public static string SaveSearchSP {
            get {
                return ResourceManager.GetString("SaveSearchSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveSuggestion.
        /// </summary>
        public static string SaveSuggestionAPI {
            get {
                return ResourceManager.GetString("SaveSuggestionAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_SaveSuggestion.
        /// </summary>
        public static string SaveSuggestionSP {
            get {
                return ResourceManager.GetString("SaveSuggestionSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_SaveUserDocument.
        /// </summary>
        public static string SaveUserDocSP {
            get {
                return ResourceManager.GetString("SaveUserDocSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outreach project key for token validation.
        /// </summary>
        public static string SecretKey {
            get {
                return ResourceManager.GetString("SecretKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {MethodName} Service executed successfully..
        /// </summary>
        public static string ServiceExecutedSuccessfully {
            get {
                return ResourceManager.GetString("ServiceExecutedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {MethodName} service starts.
        /// </summary>
        public static string ServiceExecuteStart {
            get {
                return ResourceManager.GetString("ServiceExecuteStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_SaveUser.
        /// </summary>
        public static string SignUpSP {
            get {
                return ResourceManager.GetString("SignUpSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SingUp.
        /// </summary>
        public static string SingUp {
            get {
                return ResourceManager.GetString("SingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored procedure {SPName} end.
        /// </summary>
        public static string SPExecutionEnd {
            get {
                return ResourceManager.GetString("SPExecutionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored procedure {SPName} start.
        /// </summary>
        public static string SPExecutionStart {
            get {
                return ResourceManager.GetString("SPExecutionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatusUpdateInvitee.
        /// </summary>
        public static string StatusUpdateInvitee {
            get {
                return ResourceManager.GetString("StatusUpdateInvitee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuggestionSave.
        /// </summary>
        public static string SuggestionSaveMethod {
            get {
                return ResourceManager.GetString("SuggestionSaveMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateBusinessProfile.
        /// </summary>
        public static string UpdateBusinessProfileAPI {
            get {
                return ResourceManager.GetString("UpdateBusinessProfileAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_UpdateBusinessProfile.
        /// </summary>
        public static string UpdateBusinessProfileSP {
            get {
                return ResourceManager.GetString("UpdateBusinessProfileSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_UpdateInviteeStatus.
        /// </summary>
        public static string UpdateInviteeStatusSP {
            get {
                return ResourceManager.GetString("UpdateInviteeStatusSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_UpdateUserProfile.
        /// </summary>
        public static string UpdateProfileSP {
            get {
                return ResourceManager.GetString("UpdateProfileSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UploadFiles.
        /// </summary>
        public static string UploadFiles {
            get {
                return ResourceManager.GetString("UploadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already favs this Restaurant..
        /// </summary>
        public static string UserAlreadyFavRestrRestaurant {
            get {
                return ResourceManager.GetString("UserAlreadyFavRestrRestaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user already claim this Business..
        /// </summary>
        public static string UserClaimedBusiness {
            get {
                return ResourceManager.GetString("UserClaimedBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserDeleteDocument.
        /// </summary>
        public static string UserDeleteDocument {
            get {
                return ResourceManager.GetString("UserDeleteDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User document already exist..
        /// </summary>
        public static string UserDocExist {
            get {
                return ResourceManager.GetString("UserDocExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Document does not exist..
        /// </summary>
        public static string UserDocumentNotExist {
            get {
                return ResourceManager.GetString("UserDocumentNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exist..
        /// </summary>
        public static string UserExist {
            get {
                return ResourceManager.GetString("UserExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId or RestaurantId not exist..
        /// </summary>
        public static string UserIdOrRestraIdNotExist {
            get {
                return ResourceManager.GetString("UserIdOrRestraIdNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not claimed business..
        /// </summary>
        public static string UserNotClaimBusiness {
            get {
                return ResourceManager.GetString("UserNotClaimBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exist..
        /// </summary>
        public static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user not saved contact..
        /// </summary>
        public static string UserNotSaveContactMessage {
            get {
                return ResourceManager.GetString("UserNotSaveContactMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile update successfully..
        /// </summary>
        public static string UserProfileUpdate {
            get {
                return ResourceManager.GetString("UserProfileUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_SaveUserandRestaurantSearch.
        /// </summary>
        public static string UserSignResturentSearch {
            get {
                return ResourceManager.GetString("UserSignResturentSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserSignUp.
        /// </summary>
        public static string UserSignUp {
            get {
                return ResourceManager.GetString("UserSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserValidate.
        /// </summary>
        public static string UserValidate {
            get {
                return ResourceManager.GetString("UserValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string Validate {
            get {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
    }
}
